Test api refactor
szeged/devices pull request #1
Opened 2016-09-20 08:55 UTC by zakorgy

1. The structs are replaced with enums, to allow the usage of multiple GATT  types (a mock and a platform specific) at the same time. 
2. Using two macros (one for the default functions, and one for the test functions) to make the code size shorter.
3. The `get_includes` service function has been refactored, do to the missing device attribute in the new `BluetoothService` enum types. Now it needs a `Bluetoothdevice` type as a parameter.
4. The `bluetooth-test` feature is optional and can build in pair with a platform specific configuration.

2016-09-20 10:34 UTC, dati91 commented on src/bluetooth.rs
> +macro_rules! get_inner_and_call_test_func {
If this only used in `#[cfg(feature = "bluetooth-test")]` functions, this should be guarded as well.

2016-09-20 10:35 UTC, dati91 commented on src/bluetooth.rs
> +            &BluetoothAdapter::Mock(ref fake_adapter) => fake_adapter.set_id(id),
To remain consistent, we should use `get_inner_and_call_test_func` here as well.

2016-09-20 10:36 UTC, dati91 commented on src/bluetooth.rs
> +            &BluetoothAdapter::Mock(ref fake_adapter) => fake_adapter.is_present(),
Same as above

2016-09-20 10:38 UTC, dati91 commented on src/bluetooth.rs
> +    #[cfg(feature = "bluetooth-test")]
Are you sure about this `cfg`?

2016-09-20 10:39 UTC, dati91 commented on src/bluetooth.rs
> +            &BluetoothDevice::Mock(ref fake_device) => fake_device.set_id(id),
use macro

2016-09-20 10:42 UTC, dati91 commented on src/bluetooth.rs
> +            &BluetoothGATTService::Mock(ref fake_service) => fake_service.set_uuid(uuid),
use macro

2016-09-20 10:46 UTC, dati91 requested changes
I made some comment about the current code.
And it seems to me that some of the `setter` functions are missing. Is it intentional or maybe i just missed something?

2016-09-20 11:14 UTC, zakorgy commented on src/bluetooth.rs
> +            &BluetoothAdapter::Mock(ref fake_adapter) => fake_adapter.is_present(),
I think I just missed this part.

2016-09-20 11:15 UTC, zakorgy commented on src/bluetooth.rs
> +    #[cfg(feature = "bluetooth-test")]
Indeed, this must be removed

2016-09-20 11:15 UTC, zakorgy commented on src/bluetooth.rs
> +    #[cfg(feature = "bluetooth-test")]
Indeed, this must be removed.

2016-09-20 11:15 UTC, zakorgy commented on src/bluetooth.rs
> +            &BluetoothAdapter::Mock(ref fake_adapter) => fake_adapter.set_id(id),
This function has a different return type, than the others using the `get_inner_and_call_test_func`. But if I add one more case to the macro, we can use it here as well.

2016-09-20 11:16 UTC, zakorgy commented on src/bluetooth.rs
> +macro_rules! get_inner_and_call_test_func {
We can guard the entire macro definition.

2016-09-20 11:41 UTC, dati91 commented on src/bluetooth.rs
> +    ($enum_value: expr, $enum_type: ident, set_id, $value: expr) => {
definitely revert this :)

2016-09-21 10:47 UTC, dati91 approved these changes

2016-09-21 10:48 UTC, merged